name: Final project. Infrastructure pipeline
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
defaults:
    run:
        shell: bash
jobs:
    initialise-infra:
        name: 'Init. infrastructure'
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        steps:
            - name: 'Checkout repository'
              uses: actions/checkout@v4
            
            - name: 'Setup Terraform'
              uses: hashicorp/setup-terraform@v2

            - name: 'Init. Terraform'
              working-directory: ./environments/staging
              run: |
                terraform fmt
                terraform init
            
            - name: 'Apply infrastructure'
              working-directory: ./environments/staging
              run: terraform apply -auto-approve
